# Generated by Django 4.1.5 on 2023-02-01 15:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals_gisib', '0002_signal_historicalsignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEPRCurative',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('gisib_id', models.BigIntegerField()),
                ('original_request', models.JSONField()),
                ('original_response', models.JSONField()),
                ('status_id', models.BigIntegerField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                                                  max_length=1)),
                ('collection_item', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                      on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                      to='signals_gisib.collectionitem')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                             on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                             to='signals_gisib.signal')),
            ],
            options={
                'verbose_name': 'historical epr curative',
                'verbose_name_plural': 'historical epr curatives',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EPRCurative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gisib_id', models.BigIntegerField()),
                ('original_request', models.JSONField()),
                ('original_response', models.JSONField()),
                ('status_id', models.BigIntegerField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('collection_item', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                                      to='signals_gisib.collectionitem')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epr_curative',
                                             to='signals_gisib.signal')),
            ],
        ),
    ]
