version: "3.9"

services:
  app: &app
    build:
      context: .
      target: dev
    ports:
      - "8001:8000"
    depends_on:
      postgis:
        condition: service_healthy
    environment:
      - SECRET_KEY=insecure
      - DJANGO_DEBUG=false
      - DATABASE_HOST=postgis
      - DATABASE_PORT=5432
      - DATABASE_USER=signals-gisib
      - DATABASE_PASSWORD=insecure
      - GISIB_ENDPOINT=
      - GISIB_USERNAME=
      - GISIB_PASSWORD=
      - GISIB_APIKEY=
    volumes:
      - ./app:/app/
      - ./docker-compose/run.sh:/run.sh
    command: /run.sh

  postgis:
    image: postgis/postgis:15-3.3
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: signals-gisib
      POSTGRES_USER: signals-gisib
      POSTGRES_PASSWORD: insecure
    volumes:
      - postgis-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U signals-gisib -d signals-gisib'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  celery: &celery
    <<: *app
    ports:
      - "8002:8000"
    depends_on:
      postgis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: celery -A main worker -l debug

  celery-beat:
    <<: *celery
    ports:
      - "8003:8000"
    command: celery -A main beat -l debug --pidfile /tmp/celerybeat.pid

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5673:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret cookie here'
      - RABBITMQ_DEFAULT_USER=signals-gisib-ams
      - RABBITMQ_DEFAULT_PASS=insecure
      - RABBITMQ_DEFAULT_VHOST=vhost
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgis-data:
