image:
  tag: latest

replicaCount: 1

auth:
  postgresPassword: insecure
  database: signals-gisib

volumePermissions:
  enabled: true

primary:
  persistence:
    enabled: false
    size: 1Gi
    existingClaim: null