# Generated by Django 4.1.5 on 2023-02-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_gisib', '0003_historicaleprcurative_eprcurative'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsignal',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signal',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
