# Generated by Django 4.1.7 on 2023-04-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals_gisib', '0004_historicalsignal_processed_signal_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsignal',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
