# Generated by Django 4.1.8 on 2023-04-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals_gisib', '0005_historicalsignal_processed_at_signal_processed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsignal',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='processed',
        ),
    ]
