{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: signals-gisib-ams-secrets
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.SECRET_KEY | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.secrets.DATABASE_PASSWORD | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.RABBITMQ_PASSWORD| b64enc | quote }}
  GISIB_APIKEY: {{ .Values.secrets.GISIB_APIKEY | b64enc | quote }}
  GISIB_PASSWORD: {{ .Values.secrets.GISIB_PASSWORD | b64enc | quote }}
  KEYCLOAK_CLIENT_ID: {{ .Values.secrets.KEYCLOAK_CLIENT_ID | b64enc | quote }}
  KEYCLOAK_CLIENT_SECRET_KEY: {{ .Values.secrets.KEYCLOAK_CLIENT_SECRET_KEY | b64enc | quote }}
{{- end }}
