name: CI
on: [push, pull_request]

jobs:
  test:
    name: Unit tests, Flake8 and Isort
    runs-on: ubuntu-latest

    services:
      database:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_DB: signals-gisib
          POSTGRES_USER: signals-gisib
          POSTGRES_PASSWORD: insecure

        ports: ['54321:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install geospatial libraries # https://docs.djangoproject.com/en/4.1/ref/contrib/gis/install/geolibs/
        run: sudo apt update && sudo apt install binutils libproj-dev gdal-bin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-pep517 -r requirements_test.txt

      - name: Run tests
        env:
          DATABASE_HOST: localhost
        run: |
          cd app/
          tox

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: /tmp/test/htmlcov/
