name: CI
on: [push, pull_request]

jobs:
  test:
    name: Unit tests, Flake8 and Isort
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compose-version: [ 1.0.32 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          curl -L https://raw.githubusercontent.com/docker/compose-cli/v${{ matrix.compose-version }}/scripts/install/install_linux.sh | sh
        shell: bash

      - name: Build Docker images
        run: docker-compose build

      - name: Run tests
        run: docker-compose run app tox
